# Generated by Django 5.2.10 on 2026-04-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krovlya_pages', '0002_manufacturer_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна бренда'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='manufacturers/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='product',
            name='back_side',
            field=models.CharField(blank=True, max_length=200, verbose_name='Обратная сторона'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating',
            field=models.CharField(blank=True, max_length=200, verbose_name='Покрытие'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_thickness',
            field=models.CharField(blank=True, max_length=100, verbose_name='Толщина покрытия'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет (RAL)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цветовой оттенок'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна бренда'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_production',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='product',
            name='form_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип формы'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=100, verbose_name='Длина изделия'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для отображения скидки', max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(default='шт.', help_text='шт., м², м.п., лист и т.д.', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='profile_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вид профиля кровельного материала'),
        ),
        migrations.AddField(
            model_name='product',
            name='protective_layer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Защитный слой'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='product',
            name='resistance',
            field=models.CharField(blank=True, max_length=200, verbose_name='Стойкость'),
        ),
        migrations.AddField(
            model_name='product',
            name='roof_angle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Угол наклона кровли'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_height',
            field=models.CharField(blank=True, max_length=100, verbose_name='Высота ступеньки'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_pitch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Шаг ступеньки'),
        ),
        migrations.AddField(
            model_name='product',
            name='surface_gloss',
            field=models.CharField(blank=True, max_length=100, verbose_name='Блеск поверхности'),
        ),
        migrations.AddField(
            model_name='product',
            name='surface_texture',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текстура поверхности'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, max_length=100, verbose_name='Толщина'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_appearance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гарантия на внешний вид'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_technical',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гарантия на технические характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='wave_height',
            field=models.CharField(blank=True, max_length=100, verbose_name='Высота волны'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ширина общая'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_working',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ширина рабочая'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='krovlya_pages.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['order'],
            },
        ),
    ]
